### ISSUE TITLE
fonts missing from thirdpartylibs.xml file

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-mod_certificatebeautiful#10]
you have a bunch of 3rd party fonts included in your plugin which should be covered in your thirdpartylibs.xml file.

**Comment by danmarsden** [comment]
also tui/toastr/jquery in that _editor folder... and that _editor folder includes Moodle code you have written so you shouldn't just have _editor listed on it's own as being a 3rd party lib in your xml file.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/bff30c32ec26cdf98460174d97875f1b26166e54
