### ISSUE TITLE
Missed Privacy API implementation for certificatebeautiful_issue table

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-mod_certificatebeautiful#17]
Hello,
'userid' exists in certificatebeautiful_issue table and it is require fully implement Privacy API with data export/deletion.
![image](https://github.com/user-attachments/assets/bc7fe322-e3bf-4050-9abb-4e87993759e6)

Please review more details:
https://moodledev.io/docs/4.5/apis/subsystems/privacy#plugins-which-store-personal-data

You can validate the implemented API with CLI scripts: https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils.

**Comment by eduardokraus** [comment]
This was tough
