### ISSUE TITLE
Incorrect camel case in some string

### ISSUE THREAD

**Issue by purnendudash** [EduardoKrausME/moodle-mod_certificatebeautiful#2]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Your use case 
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/blob/55c90966d8e638e04288206f7175775754e4e888/lang/en/certificatebeautiful.php#L62

Note: this is not a blocker for approval in the plugins db.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/b2e8328cc88cd9efdd98968bbb97fdcde0ed110d
