### ISSUE TITLE
Signature text problem

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-mod_certificatebeautiful#22]
Hi,
I love your plugin.
But when I tried to use the signature text feature (Moodle 4.5 in localhost), it gives me an error after I type the first character.
CAn you please check this, as it would be a very nice feature to have available

**Comment by eduardokraus** [comment]
¿Podrías proporcionar una captura de pantalla para que pueda verificar?

**Comment by germanvaleroelizondo** [comment]
![imagen](https://github.com/user-attachments/assets/69110bb0-bdc3-4cbc-a8e3-4adbe363c532)
