### ISSUE TITLE
Missing boilerplates/copyrights

### ISSUE THREAD

**Issue by purnendudash** [EduardoKrausME/moodle-mod_certificatebeautiful#3]
All plugin file should have some common explicit GPL license statement. Kindly check and include the same.

For more information on this see:
https://moodledev.io/general/community/plugincontribution/checklist#boilerplate

Reference 
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/blob/55c90966d8e638e04288206f7175775754e4e888/classes/pdf/replace_tags.php#L18

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/d31f9b6364519c2b6c9c5db7a0bc9c3f816da597
