### ISSUE TITLE
Incorrect use of styles.css 

### ISSUE THREAD

**Issue by purnendudash** [EduardoKrausME/moodle-mod_certificatebeautiful#4]
Kindly follow this doc for further reference

https://moodledev.io/docs/apis/commonfiles#stylescss

Also it include some generic styles. 

`.report-btn-small {
`
Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/197d0fd6bc5953f9edf1ba8aca67bcc0ad4dfcaa
