### ISSUE TITLE
Missing thirdpartylibs.xml file.

### ISSUE THREAD

**Issue by purnendudash** [EduardoKrausME/moodle-mod_certificatebeautiful#5]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://moodledev.io/docs/apis/commonfiles#thirdpartylibsxml
And here:
https://moodledev.io/general/community/plugincontribution/thirdpartylibraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is a blocker for approval in the plugins db.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/a969815655671230b442a3fd9d1bee1dcad9cd92
