### ISSUE TITLE
Classname was being extended in the same name

### ISSUE THREAD

**Issue by purnendudash** [EduardoKrausME/moodle-mod_certificatebeautiful#6]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/blob/55c90966d8e638e04288206f7175775754e4e888/classes/event/course_module_viewed.php#L37

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/ee9d7a5a6bf90aa113b08b78a749a473f1eab863

**Comment by mudrd8mz** [comment]
For the record, I don't think this was necessary. As Eduardo says, it is common to do this in namespaced classes.

**Comment by purnendudash** [comment]
@mudrd8mz thanks and noted.
