### ISSUE TITLE
Second level namespace violate the naming rules

### ISSUE THREAD

**Issue by mudrd8mz** [EduardoKrausME/moodle-mod_certificatebeautiful#9]
Please refer to https://moodledev.io/general/development/policies/codingstyle#rules-for-level2

Your custom namespaces like `fonts`, `help`, `model`, `pdf`, `report` or `vo` violate this naming rule. There are good reasons why it should be followed, mainly to avoid potential conflicts in the future. All these should be under `classes/local/` namespace.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_certificatebeautiful/commit/a3a70e2da103553eb9fe10f81228c46c09d5b018
